# Generated by Django 3.0.7 on 2020-06-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200623_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/anonymous.png', upload_to='images/'),
        ),
    ]
